# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: RIoTPoT GSoC 2022
subtitle: Version 1.0
email: ricardoyaben@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Blogpost for my experience with RIoTPoT as contributor for GSoC 2022 in collaboration with the HoneyNet project
twitter_username: ric.yaben
github_username: RicYaben
minimal_mistakes_skin: dark
search: true

# Meta
name: Ricardo Yaben
url: "https://ryaben17.github.io"
baseurl: "/riotpot-gsoc_2022"
repository: aau-network-security/riotpot/tree/gsoc_2022

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author: &ric
  name: Ricardo Yaben
  avatar: "/assets/images/bio.png"
  bio: "**(He/Him)**\nGSoC 2022 Contributor\nMSc in Cyber Security\nCyber Security Consultant at EY"
  links: &links
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ricardo-yaben-lopezosa-aa63a2159"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ricyaben"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/@RYaben"

footer:
  links: *links

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      author: Ricardo Yaben

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      author: Ricardo Yaben

  # _docs
  - scope:
      path: "_docs"
      type: pages
    values:
      layout: single
      toc: true
      sidebar:
        nav: "docs"
      author: Ricardo Yaben

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
