# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ricardo Yaben
subtitle: Cyber Security Adventures
email: ricardoyaben@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Blogpost for my experience as a Cyber Security MSc.
  Contains information in projects such as RIoTPoT, as part of my participation in the GSoC 2022 as a Contributor
  in collaboration with the Honeynet project.
twitter_username: ric.yaben
github_username: RicYaben
minimal_mistakes_skin: dark
search: true

# Meta
name: Ricardo Yaben
url: "https://ryaben17.github.io"
baseurl: "/riotpot-gsoc_2022"
repository: aau-network-security/riotpot

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - .htaccess

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

footer:
  links: *links

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      share: true
      related: true
      author_profile: true
      author: Ricardo Yaben

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      author: Ricardo Yaben

  # _portfolio
  - scope:
      path: "_portfolio"
      type: portfolio
    values:
      layout: single
      share: true

  # _projects
  - scope:
      path: _projects
      type: projects
    values:
      layout: single
      toc: true
      author: Ricardo Yaben

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
