# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#title: Ricardo Yaben
email: ricardoyaben@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ricardo Yaben official site.
twitter_username: ric.yaben
github_username: RicYaben
minimal_mistakes_skin: custom
search: true

social:
  type: Person
  name: Ricardo Yaben
  links:
    - https://www.linkedin.com/in/ricardo-yaben-lopezosa-aa63a2159
    - https://github.com/ricyaben
    - https://twitter.com/@RYaben

# Meta
name: Ricardo Yaben
url: "https://ricyaben.github.io"
baseurl: "/"
repository: ryaben/blog
logo: /assets/images/logo.svg

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

atom_feed:
  hide: true

include:
  - _pages
  - .htaccess

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Scripts for footer and header
# head_scripts:
# footer_scripts:

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ricardo-yaben-lopezosa-aa63a2159"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ricyaben"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/@RYaben"

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      share: true
      related: true

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single

  # _portfolio
  - scope:
      path: "_portfolio"
      type: portfolio
    values:
      layout: single
      share: true

  # _projects
  - scope:
      path: _projects
      type: projects
    values:
      layout: single
      toc: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
